Visual move
===========

// Visual moving files

Утилита для наглядного перемещения файлов по каталогам, когда это необходимо делать в ручную.

Работает на Windows. Установка не требуется, зависимостей нет.

Распространяется по лицензии http://www.gnu.org/licenses/gpl-3.0.html[GNU GPL 3]

*[red]#ВАЖНО!!! ВЫ ИСПОЛЬЗУЕТЕ ДАННЫЙ ПРОГРАММНЫЙ ПРОДУКТ НА СВОЙ СТРАХ И РИСК!!!#*

*Автор заранее слагает с себя ответственность за весь возможный ущерб, причиненный программой.*

*This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.*


Описание
--------

Программа позволяет пользователю наглядно перемещать файлы из заданных каталогов.

Все настройки производятся через ini файл. 

Настройки перемещений файлов делятся на блоки, которые задают каталоги перемещения, направление перемещения, маски файлов.

Количество блоков перемещений неограничено. Сколько будет задано блоков, столько и отобразится в интерфейсе.

Возможно ведение лога перемещений в подкаталоге Log программы. Файлы логов назваются по дате, один файл - один день. Файлы логов не удаляются.

Контроль существования каталогов при запуске программы не производится.

Общие настройки
---------------

Задаются в секции 'settings'

BackupEnabled::
 Вкл/выкл резервного копирования перемещаемых файлов. Может быть true,false (по умолчанию false)
BackupDir::
 Каталог резервного копирования
RefreshInterval::
 Период обновления содержимого каталогов в секундах, если 0 (по умолчанию) то обновления нет 
ButtonLeft::
 Вкл/выкл кнопки "Все налево". Может быть true,false (по умолчанию false)
buttonRight::
 Вкл/выкл кнопки "Все направо". Может быть true,false (по умолчанию true)
buttonBoth::
 Вкл/выкл кнопки "Все в обе стороны". Может быть true,false (по умолчанию false) 
 
Настройки перемещаемых блоков
-----------------------------

Задаются в секции 'blocks'. К каждому параметру прибавляется номер блока начиная с 0.

name::
 Имя блока. Отображается программой
sourceDir::
 Каталог источник (слева) 
destDir::
 Каталог приемник (справа) 
sourceMask::
 Маска файлов источника, если не указана, то все файлы. Если нужно указать несколько масок, разделяйте их вертикальной чертой "|" 
direction::
 Направление перемещения файлов left, right, both. Если не указано - right 
destMask::
 Маска файлов приемника. Указывается так же как маска для источника.

 
.Пример настроек ini файла с двумя блоками
===============================
-------------------------------
[settings] 
; Вкл/выкл резервного копирования перемещаемых файлов 
BackupEnabled=false 
; Каталог резервного копирования 
BackupDir=D:/Backup/%yyMMdd% 
; Период обновления содержимого каталогов, если 0 то обновления нет 
refreshInterval=20 
; Вкл/выкл кнопки "Все налево" 
ButtonLeft=false 
; Вкл/выкл кнопки "Все направо" 
buttonRight=true 
; Вкл/выкл кнопки "Все в обе стороны" 
buttonBoth=false 

; Блоки. Каждый блок - набор строк с номером блока в имени, начиная с 0 
; Количество блоков неограничено 
[blocks] 
; Имя 
name0=Тестовое название 1 
; Каталог источник (слева) 
sourceDir0=d:/temp/1 
; Каталог приемник (справа) 
destDir0=d:/temp/1/2 
; Маска файлов источника, если не указана, то все файлы 
;sourceMask0=*.txt ; Можно так mask0=*.rar|*.txt 
; Направление перемещения файлов left, right, both. Если не указано - right 
;direction0=left 
; Маска файлов приемника 
;destMask=*.txt 

name1=Тест 2 
sourceDir1=d:/test/2 
destDir1=d:/test/3 
sourceMask1=*.rar 
;direction1=left 
-------------------------------
===============================

Ссылки
------

Написано на http://qt.nokia.com/[Qt].

Контакты 
--------

Вопросы, предложения, замечания принимаются по адресу atsave@narod.ru    +  
Сайт программы: http://atsave.narod.ru
